### ISSUE TITLE
Merge LibGAP.jl into GAPJulia ?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAPJulia#32]
... as discussed during GAP Days Fall 2018

**Comment by sebasguts** [comment]
Currently, the Julia package manager seems to be very strict about the structure of a Julia module.
It needs to have a `deps` folder and `Manifest.toml` and `Project.toml` in its root folder.
So how would we want to unify it?

Currently, `LibGAP.jl` is not a proper Julia module at all. We could just make it another subfolder in this repo, and be okay with that we could currently not use it as a proper Julia module, or giving the whole Repo the structure of a Julia module and just having the two GAP packages around.

**Comment by wbhart** [comment]
I my opinion, it is worth thinking about whether a separate LibGAP package could have wider benefits for the community at large. I had always envisioned the two being a single Julia package, but it need not be that way if there is a good reason to keep them separated.

In short, you may increase the usership of GAP in the Julia community with one or the other approach.

**Comment by ThomasBreuer** [comment]
`LibGAP.jl` and GAP's `GAPJulia` package belong together because they provide the two directions
of an interface between GAP and Julia, thus one wants to have them together;
from the viewpoint of Julia, it would be strange if one could not call some GAP functionality
just because it needs Julia.
(But this is only a logical dependency not a technical one,
and it would not cause real problems to have separate repositories for `LibGAP.jl` and `GAPJulia`
as long as there are no technical dependencies.)

If Julia wants the repository of a Julia module to have a particular structure,
can't we provide a repository with that structure for `LibGAP.jl` and then add the stuff from `GAPJulia` to it,
and Julia's package manager will be happy?
(This is how I interpret the last part in the above comment by @sebasguts.)

**Comment by sebasguts** [comment]
Yes, that is indeed correct. We could even still pack it in GAP's `pkg` folder. It would just look ugly.

**Comment by fingolfin** [comment]
I propose the following plan: First, we update https://github.com/oscar-system/LibGAP.jl to work with the current version of GAPJulia (possibly on a branch there, as to not negatively affect the work by @CarloSircana in his `CarloLibGAPTest` repo). Once that works, we simply subtree-merge this into the GAPJulia repo, into a subdir `LibGAP.jl`. 

[Alternatively, we could reverse the order, and first subtree-merge LibGAP.jl, then work on getting it to run].

In particular, I would *not* try to convert it into a proper Julia package at first, simply to reduce the size of the task; instead, let's first get to a version that actually works well again. Then, add integration tests that verify it keeps working. Once that is complete, we can worry about turning it into a proper Julia package, or not.

Thoughts?

**Comment by sebasguts** [comment]
@fingolfin Okay. I would even do it more agressive:

Lets just subtree merge LibGAP.jl now, and then make it usable again with the current GAP. I do not see any issues for @CarloSircana right now. Afterwards, we will have to fix up the `CarloLibGAPTest`.

While making this a proper Julia module might be a desirable goal, I fully agree that this is something for the future we should not try to put energy in right now. Let us first get the two parts of this project into a
maintainable and usable state.

I will do the subtree merge now, just creating a third folder in this repo.
