### ISSUE TITLE
How to organize Julia code

### ISSUE THREAD

**Issue by sebasguts** [oscar-system/GAPJulia#96]
I have been thinking lately about how to organize the Julia Interface code between `LibGAP.jl` and `JuliaInterface`. Currently, most of the code seems to be positioned arbitrary, and while `JuliaInterface` works without `LibGAP.jl`, the converse is false.

What would you think about `JuliaInterface` loading code from `LibGAP.jl`? I would then remove more Julia code from `JuliaInterface` and move it to `LibGAP.jl`. Or do you regard it bad practice if `JuliaInterface` loads code that is not in its package folder?

**Comment by wbhart** [comment]
That would probably depend on whether you want to make these standard Julia packages or not. As a standard Julia package it certainly couldn't depend on code not in the package, unless that other package is in the REQUIRE file.

One has to be a little careful how sharing of code happens. Julia can be installed on virtual machines and clusters. Also, a lot of system admins will install Julia for their users and then install a bunch of packages their users most commonly use, to cut down the number of duplicate versions of those packages there are. But then individual users can have their own packages too. So that means one has to be careful how one goes looking for the code from another package. One simply can't assume it is in the user's local .julia directory.

How this all works with pkg3, I'm not too sure.

**Comment by sebasguts** [comment]
Currently I do not see any problems with making this a Julia package, as all of this could be handled as "external" dependency. (I.e., GAP). I was more worried about making `JuliaInterface` a GAP package.

**Comment by ThomasBreuer** [comment]
I think that users of `JuliaInterface` will probably need `LibGAP.jl`
because of its `from_gap` and `to_gap` functions.
Thus it would be good to guarantee that `LibGAP.jl` is always available.
And then it does not really matter where the actual code resides.

(By the way, we must be able to express, for GAP packages that rely on `JuliaInterface`,
which Julia packages are needed.
The GAP package can then decide whether it is loadable or not.
Perhaps this is another issue.)

**Comment by wbhart** [comment]
Ok, I misunderstood. I thought you were talking about having a Julia package for loading JuliaInterface, and then loading that from LibGAP.jl. Of course your question makes a lot more sense now.

**Comment by sebasguts** [comment]
This is done in #97 for now
